### ISSUE TITLE
Rec dev plots

### ISSUE THREAD

**Issue by KyleShertzer-NOAA** [mtvincen/FishGraph#19]
In function BSR.time.plots, the rec dev plot shows deviations in all years, with zeros in years where the devs weren't estimated. It would be useful to be able to drop the years with zeros. We already have start.drop as an argument in BSR.time.plots, but that applies to all plots in this function. We would need a different start.drop argument that applies only to the rec devs, and similar "last.drop" that also applies to rec devs for when we want to remove zeros at the end of the time series.

This isn't a bug at all, just a "nice to have" feature.

**Comment by mtvincen** [comment]
Would it make more sense to make a minor tweak to BAM so that you don't need to worry about it on the backend?
If you put 
  log_rec_dev_output=missing;
in the line after
  log_rec_dev_output.initialize();
then when you plot it using the existing function there won't be any zeros. But I could add in some functionality if you think it's useful enough.

**Comment by KyleShertzer-NOAA** [comment]
Yes, that does the trick. I was initially thinking we'd want it in FG so that it was an option without having to re-run BAM to flip it on or off, but I guess I can't think of a good reason why we'd want to plot those zero values.

**Comment by mtvincen** [comment]
Note that the NAs cause an issue with the projection code since the last year recruitment dev is now NA and will make the abundance be NA.
